# AllOfUs Client API
#
# The API used by AllOfUs workbench clients (including both notebooks and our UI.)
#
# OpenAPI spec version: 0.1.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' AnnotationQuery Class
#'
#' @field columns 
#' @field orderBy 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
AnnotationQuery <- R6::R6Class(
  'AnnotationQuery',
  public = list(
    `columns` = NULL,
    `orderBy` = NULL,
    initialize = function(`columns`, `orderBy`){
      if (!missing(`columns`)) {
        stopifnot(is.list(`columns`), length(`columns`) != 0)
        lapply(`columns`, function(x) stopifnot(is.character(x)))
        self$`columns` <- `columns`
      }
      if (!missing(`orderBy`)) {
        stopifnot(is.list(`orderBy`), length(`orderBy`) != 0)
        lapply(`orderBy`, function(x) stopifnot(is.character(x)))
        self$`orderBy` <- `orderBy`
      }
    },
    toJSON = function() {
      AnnotationQueryObject <- list()
      if (!is.null(self$`columns`)) {
        AnnotationQueryObject[['columns']] <- self$`columns`
      }
      if (!is.null(self$`orderBy`)) {
        AnnotationQueryObject[['orderBy']] <- self$`orderBy`
      }

      AnnotationQueryObject
    },
    fromJSON = function(AnnotationQueryJson) {
      AnnotationQueryObject <- jsonlite::fromJSON(AnnotationQueryJson)
      if (!is.null(AnnotationQueryObject$`columns`)) {
        self$`columns` <- AnnotationQueryObject$`columns`
      }
      if (!is.null(AnnotationQueryObject$`orderBy`)) {
        self$`orderBy` <- AnnotationQueryObject$`orderBy`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "columns": [%s],
           "orderBy": [%s]
        }',
        lapply(self$`columns`, function(x) paste(paste0('"', x, '"'), sep=",")),
        lapply(self$`orderBy`, function(x) paste(paste0('"', x, '"'), sep=","))
      )
    },
    fromJSONString = function(AnnotationQueryJson) {
      AnnotationQueryObject <- jsonlite::fromJSON(AnnotationQueryJson)
      self$`columns` <- AnnotationQueryObject$`columns`
      self$`orderBy` <- AnnotationQueryObject$`orderBy`
    }
  )
)
