# AllOfUs Client API
#
# The API used by AllOfUs workbench clients (including both notebooks and our UI.)
#
# OpenAPI spec version: 0.1.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' CohortStatus Class
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
CohortStatus <- R6::R6Class(
  'CohortStatus',
  public = list(
    initialize = function(){
    },
    toJSON = function() {
      CohortStatusObject <- list()

      CohortStatusObject
    },
    fromJSON = function(CohortStatusJson) {
      CohortStatusObject <- jsonlite::fromJSON(CohortStatusJson)
    },
    toJSONString = function() {
       sprintf(
        '{
        }',
      )
    },
    fromJSONString = function(CohortStatusJson) {
      CohortStatusObject <- jsonlite::fromJSON(CohortStatusJson)
    }
  )
)
