# AllOfUs Client API
#
# The API used by AllOfUs workbench clients (including both notebooks and our UI.)
#
# OpenAPI spec version: 0.1.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' ColumnFilter Class
#'
#' @field columnName 
#' @field operator 
#' @field value 
#' @field values 
#' @field valueDate 
#' @field valueNumber 
#' @field valueNumbers 
#' @field valueNull 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ColumnFilter <- R6::R6Class(
  'ColumnFilter',
  public = list(
    `columnName` = NULL,
    `operator` = NULL,
    `value` = NULL,
    `values` = NULL,
    `valueDate` = NULL,
    `valueNumber` = NULL,
    `valueNumbers` = NULL,
    `valueNull` = NULL,
    initialize = function(`columnName`, `operator`, `value`, `values`, `valueDate`, `valueNumber`, `valueNumbers`, `valueNull`){
      if (!missing(`columnName`)) {
        stopifnot(is.character(`columnName`), length(`columnName`) == 1)
        self$`columnName` <- `columnName`
      }
      if (!missing(`operator`)) {
        stopifnot(R6::is.R6(`operator`))
        self$`operator` <- `operator`
      }
      if (!missing(`value`)) {
        stopifnot(is.character(`value`), length(`value`) == 1)
        self$`value` <- `value`
      }
      if (!missing(`values`)) {
        stopifnot(is.list(`values`), length(`values`) != 0)
        lapply(`values`, function(x) stopifnot(is.character(x)))
        self$`values` <- `values`
      }
      if (!missing(`valueDate`)) {
        stopifnot(is.character(`valueDate`), length(`valueDate`) == 1)
        self$`valueDate` <- `valueDate`
      }
      if (!missing(`valueNumber`)) {
        self$`valueNumber` <- `valueNumber`
      }
      if (!missing(`valueNumbers`)) {
        stopifnot(is.list(`valueNumbers`), length(`valueNumbers`) != 0)
        lapply(`valueNumbers`, function(x) stopifnot(is.character(x)))
        self$`valueNumbers` <- `valueNumbers`
      }
      if (!missing(`valueNull`)) {
        self$`valueNull` <- `valueNull`
      }
    },
    toJSON = function() {
      ColumnFilterObject <- list()
      if (!is.null(self$`columnName`)) {
        ColumnFilterObject[['columnName']] <- self$`columnName`
      }
      if (!is.null(self$`operator`)) {
        ColumnFilterObject[['operator']] <- self$`operator`$toJSON()
      }
      if (!is.null(self$`value`)) {
        ColumnFilterObject[['value']] <- self$`value`
      }
      if (!is.null(self$`values`)) {
        ColumnFilterObject[['values']] <- self$`values`
      }
      if (!is.null(self$`valueDate`)) {
        ColumnFilterObject[['valueDate']] <- self$`valueDate`
      }
      if (!is.null(self$`valueNumber`)) {
        ColumnFilterObject[['valueNumber']] <- self$`valueNumber`
      }
      if (!is.null(self$`valueNumbers`)) {
        ColumnFilterObject[['valueNumbers']] <- self$`valueNumbers`
      }
      if (!is.null(self$`valueNull`)) {
        ColumnFilterObject[['valueNull']] <- self$`valueNull`
      }

      ColumnFilterObject
    },
    fromJSON = function(ColumnFilterJson) {
      ColumnFilterObject <- jsonlite::fromJSON(ColumnFilterJson)
      if (!is.null(ColumnFilterObject$`columnName`)) {
        self$`columnName` <- ColumnFilterObject$`columnName`
      }
      if (!is.null(ColumnFilterObject$`operator`)) {
        operatorObject <- Operator$new()
        operatorObject$fromJSON(jsonlite::toJSON(ColumnFilterObject$operator, auto_unbox = TRUE))
        self$`operator` <- operatorObject
      }
      if (!is.null(ColumnFilterObject$`value`)) {
        self$`value` <- ColumnFilterObject$`value`
      }
      if (!is.null(ColumnFilterObject$`values`)) {
        self$`values` <- ColumnFilterObject$`values`
      }
      if (!is.null(ColumnFilterObject$`valueDate`)) {
        self$`valueDate` <- ColumnFilterObject$`valueDate`
      }
      if (!is.null(ColumnFilterObject$`valueNumber`)) {
        self$`valueNumber` <- ColumnFilterObject$`valueNumber`
      }
      if (!is.null(ColumnFilterObject$`valueNumbers`)) {
        self$`valueNumbers` <- ColumnFilterObject$`valueNumbers`
      }
      if (!is.null(ColumnFilterObject$`valueNull`)) {
        self$`valueNull` <- ColumnFilterObject$`valueNull`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "columnName": %s,
           "operator": %s,
           "value": %s,
           "values": [%s],
           "valueDate": %s,
           "valueNumber": %s,
           "valueNumbers": [%s],
           "valueNull": %s
        }',
        self$`columnName`,
        self$`operator`$toJSON(),
        self$`value`,
        lapply(self$`values`, function(x) paste(paste0('"', x, '"'), sep=",")),
        self$`valueDate`,
        self$`valueNumber`,
        lapply(self$`valueNumbers`, function(x) paste(paste0('"', x, '"'), sep=",")),
        self$`valueNull`
      )
    },
    fromJSONString = function(ColumnFilterJson) {
      ColumnFilterObject <- jsonlite::fromJSON(ColumnFilterJson)
      self$`columnName` <- ColumnFilterObject$`columnName`
      OperatorObject <- Operator$new()
      self$`operator` <- OperatorObject$fromJSON(jsonlite::toJSON(ColumnFilterObject$operator, auto_unbox = TRUE))
      self$`value` <- ColumnFilterObject$`value`
      self$`values` <- ColumnFilterObject$`values`
      self$`valueDate` <- ColumnFilterObject$`valueDate`
      self$`valueNumber` <- ColumnFilterObject$`valueNumber`
      self$`valueNumbers` <- ColumnFilterObject$`valueNumbers`
      self$`valueNull` <- ColumnFilterObject$`valueNull`
    }
  )
)
