# AllOfUs Client API
#
# The API used by AllOfUs workbench clients (including both notebooks and our UI.)
#
# OpenAPI spec version: 0.1.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' Concept Class
#'
#' @field conceptId 
#' @field conceptName 
#' @field domainId 
#' @field vocabularyId 
#' @field conceptCode 
#' @field conceptClassId 
#' @field standardConcept 
#' @field countValue 
#' @field prevalence 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Concept <- R6::R6Class(
  'Concept',
  public = list(
    `conceptId` = NULL,
    `conceptName` = NULL,
    `domainId` = NULL,
    `vocabularyId` = NULL,
    `conceptCode` = NULL,
    `conceptClassId` = NULL,
    `standardConcept` = NULL,
    `countValue` = NULL,
    `prevalence` = NULL,
    initialize = function(`conceptId`, `conceptName`, `domainId`, `vocabularyId`, `conceptCode`, `conceptClassId`, `standardConcept`, `countValue`, `prevalence`){
      if (!missing(`conceptId`)) {
        stopifnot(is.numeric(`conceptId`), length(`conceptId`) == 1)
        self$`conceptId` <- `conceptId`
      }
      if (!missing(`conceptName`)) {
        stopifnot(is.character(`conceptName`), length(`conceptName`) == 1)
        self$`conceptName` <- `conceptName`
      }
      if (!missing(`domainId`)) {
        stopifnot(is.character(`domainId`), length(`domainId`) == 1)
        self$`domainId` <- `domainId`
      }
      if (!missing(`vocabularyId`)) {
        stopifnot(is.character(`vocabularyId`), length(`vocabularyId`) == 1)
        self$`vocabularyId` <- `vocabularyId`
      }
      if (!missing(`conceptCode`)) {
        stopifnot(is.character(`conceptCode`), length(`conceptCode`) == 1)
        self$`conceptCode` <- `conceptCode`
      }
      if (!missing(`conceptClassId`)) {
        stopifnot(is.character(`conceptClassId`), length(`conceptClassId`) == 1)
        self$`conceptClassId` <- `conceptClassId`
      }
      if (!missing(`standardConcept`)) {
        self$`standardConcept` <- `standardConcept`
      }
      if (!missing(`countValue`)) {
        stopifnot(is.numeric(`countValue`), length(`countValue`) == 1)
        self$`countValue` <- `countValue`
      }
      if (!missing(`prevalence`)) {
        stopifnot(is.numeric(`prevalence`), length(`prevalence`) == 1)
        self$`prevalence` <- `prevalence`
      }
    },
    toJSON = function() {
      ConceptObject <- list()
      if (!is.null(self$`conceptId`)) {
        ConceptObject[['conceptId']] <- self$`conceptId`
      }
      if (!is.null(self$`conceptName`)) {
        ConceptObject[['conceptName']] <- self$`conceptName`
      }
      if (!is.null(self$`domainId`)) {
        ConceptObject[['domainId']] <- self$`domainId`
      }
      if (!is.null(self$`vocabularyId`)) {
        ConceptObject[['vocabularyId']] <- self$`vocabularyId`
      }
      if (!is.null(self$`conceptCode`)) {
        ConceptObject[['conceptCode']] <- self$`conceptCode`
      }
      if (!is.null(self$`conceptClassId`)) {
        ConceptObject[['conceptClassId']] <- self$`conceptClassId`
      }
      if (!is.null(self$`standardConcept`)) {
        ConceptObject[['standardConcept']] <- self$`standardConcept`
      }
      if (!is.null(self$`countValue`)) {
        ConceptObject[['countValue']] <- self$`countValue`
      }
      if (!is.null(self$`prevalence`)) {
        ConceptObject[['prevalence']] <- self$`prevalence`
      }

      ConceptObject
    },
    fromJSON = function(ConceptJson) {
      ConceptObject <- jsonlite::fromJSON(ConceptJson)
      if (!is.null(ConceptObject$`conceptId`)) {
        self$`conceptId` <- ConceptObject$`conceptId`
      }
      if (!is.null(ConceptObject$`conceptName`)) {
        self$`conceptName` <- ConceptObject$`conceptName`
      }
      if (!is.null(ConceptObject$`domainId`)) {
        self$`domainId` <- ConceptObject$`domainId`
      }
      if (!is.null(ConceptObject$`vocabularyId`)) {
        self$`vocabularyId` <- ConceptObject$`vocabularyId`
      }
      if (!is.null(ConceptObject$`conceptCode`)) {
        self$`conceptCode` <- ConceptObject$`conceptCode`
      }
      if (!is.null(ConceptObject$`conceptClassId`)) {
        self$`conceptClassId` <- ConceptObject$`conceptClassId`
      }
      if (!is.null(ConceptObject$`standardConcept`)) {
        self$`standardConcept` <- ConceptObject$`standardConcept`
      }
      if (!is.null(ConceptObject$`countValue`)) {
        self$`countValue` <- ConceptObject$`countValue`
      }
      if (!is.null(ConceptObject$`prevalence`)) {
        self$`prevalence` <- ConceptObject$`prevalence`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "conceptId": %d,
           "conceptName": %s,
           "domainId": %s,
           "vocabularyId": %s,
           "conceptCode": %s,
           "conceptClassId": %s,
           "standardConcept": %s,
           "countValue": %d,
           "prevalence": %d
        }',
        self$`conceptId`,
        self$`conceptName`,
        self$`domainId`,
        self$`vocabularyId`,
        self$`conceptCode`,
        self$`conceptClassId`,
        self$`standardConcept`,
        self$`countValue`,
        self$`prevalence`
      )
    },
    fromJSONString = function(ConceptJson) {
      ConceptObject <- jsonlite::fromJSON(ConceptJson)
      self$`conceptId` <- ConceptObject$`conceptId`
      self$`conceptName` <- ConceptObject$`conceptName`
      self$`domainId` <- ConceptObject$`domainId`
      self$`vocabularyId` <- ConceptObject$`vocabularyId`
      self$`conceptCode` <- ConceptObject$`conceptCode`
      self$`conceptClassId` <- ConceptObject$`conceptClassId`
      self$`standardConcept` <- ConceptObject$`standardConcept`
      self$`countValue` <- ConceptObject$`countValue`
      self$`prevalence` <- ConceptObject$`prevalence`
    }
  )
)
