# AllOfUs Client API
#
# The API used by AllOfUs workbench clients (including both notebooks and our UI.)
#
# OpenAPI spec version: 0.1.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' ConceptListResponse Class
#'
#' @field items 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ConceptListResponse <- R6::R6Class(
  'ConceptListResponse',
  public = list(
    `items` = NULL,
    initialize = function(`items`){
      if (!missing(`items`)) {
        stopifnot(is.list(`items`), length(`items`) != 0)
        lapply(`items`, function(x) stopifnot(R6::is.R6(x)))
        self$`items` <- `items`
      }
    },
    toJSON = function() {
      ConceptListResponseObject <- list()
      if (!is.null(self$`items`)) {
        ConceptListResponseObject[['items']] <- lapply(self$`items`, function(x) x$toJSON())
      }

      ConceptListResponseObject
    },
    fromJSON = function(ConceptListResponseJson) {
      ConceptListResponseObject <- jsonlite::fromJSON(ConceptListResponseJson)
      if (!is.null(ConceptListResponseObject$`items`)) {
        self$`items` <- lapply(ConceptListResponseObject$`items`, function(x) {
          itemsObject <- Concept$new()
          itemsObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          itemsObject
        })
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "items": [%s]
        }',
        lapply(self$`items`, function(x) paste(x$toJSON(), sep=","))
      )
    },
    fromJSONString = function(ConceptListResponseJson) {
      ConceptListResponseObject <- jsonlite::fromJSON(ConceptListResponseJson)
      self$`items` <- lapply(ConceptListResponseObject$`items`, function(x) Concept$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
    }
  )
)
