# AllOfUs Client API
#
# The API used by AllOfUs workbench clients (including both notebooks and our UI.)
#
# OpenAPI spec version: 0.1.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' Domain Class
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Domain <- R6::R6Class(
  'Domain',
  public = list(
    initialize = function(){
    },
    toJSON = function() {
      DomainObject <- list()

      DomainObject
    },
    fromJSON = function(DomainJson) {
      DomainObject <- jsonlite::fromJSON(DomainJson)
    },
    toJSONString = function() {
       sprintf(
        '{
        }',
      )
    },
    fromJSONString = function(DomainJson) {
      DomainObject <- jsonlite::fromJSON(DomainJson)
    }
  )
)
