# AllOfUs Client API
#
# The API used by AllOfUs workbench clients (including both notebooks and our UI.)
#
# OpenAPI spec version: 0.1.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' FieldSet Class
#'
#' @field tableQuery 
#' @field annotationQuery 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
FieldSet <- R6::R6Class(
  'FieldSet',
  public = list(
    `tableQuery` = NULL,
    `annotationQuery` = NULL,
    initialize = function(`tableQuery`, `annotationQuery`){
      if (!missing(`tableQuery`)) {
        stopifnot(R6::is.R6(`tableQuery`))
        self$`tableQuery` <- `tableQuery`
      }
      if (!missing(`annotationQuery`)) {
        stopifnot(R6::is.R6(`annotationQuery`))
        self$`annotationQuery` <- `annotationQuery`
      }
    },
    toJSON = function() {
      FieldSetObject <- list()
      if (!is.null(self$`tableQuery`)) {
        FieldSetObject[['tableQuery']] <- self$`tableQuery`$toJSON()
      }
      if (!is.null(self$`annotationQuery`)) {
        FieldSetObject[['annotationQuery']] <- self$`annotationQuery`$toJSON()
      }

      FieldSetObject
    },
    fromJSON = function(FieldSetJson) {
      FieldSetObject <- jsonlite::fromJSON(FieldSetJson)
      if (!is.null(FieldSetObject$`tableQuery`)) {
        tableQueryObject <- TableQuery$new()
        tableQueryObject$fromJSON(jsonlite::toJSON(FieldSetObject$tableQuery, auto_unbox = TRUE))
        self$`tableQuery` <- tableQueryObject
      }
      if (!is.null(FieldSetObject$`annotationQuery`)) {
        annotationQueryObject <- AnnotationQuery$new()
        annotationQueryObject$fromJSON(jsonlite::toJSON(FieldSetObject$annotationQuery, auto_unbox = TRUE))
        self$`annotationQuery` <- annotationQueryObject
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "tableQuery": %s,
           "annotationQuery": %s
        }',
        self$`tableQuery`$toJSON(),
        self$`annotationQuery`$toJSON()
      )
    },
    fromJSONString = function(FieldSetJson) {
      FieldSetObject <- jsonlite::fromJSON(FieldSetJson)
      TableQueryObject <- TableQuery$new()
      self$`tableQuery` <- TableQueryObject$fromJSON(jsonlite::toJSON(FieldSetObject$tableQuery, auto_unbox = TRUE))
      AnnotationQueryObject <- AnnotationQuery$new()
      self$`annotationQuery` <- AnnotationQueryObject$fromJSON(jsonlite::toJSON(FieldSetObject$annotationQuery, auto_unbox = TRUE))
    }
  )
)
