# AllOfUs Client API
#
# The API used by AllOfUs workbench clients (including both notebooks and our UI.)
#
# OpenAPI spec version: 0.1.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' MaterializeCohortRequest Class
#'
#' @field cohortName 
#' @field cohortSpec 
#' @field statusFilter 
#' @field cdrVersionName 
#' @field pageToken 
#' @field pageSize 
#' @field fieldSet 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
MaterializeCohortRequest <- R6::R6Class(
  'MaterializeCohortRequest',
  public = list(
    `cohortName` = NULL,
    `cohortSpec` = NULL,
    `statusFilter` = NULL,
    `cdrVersionName` = NULL,
    `pageToken` = NULL,
    `pageSize` = NULL,
    `fieldSet` = NULL,
    initialize = function(`cohortName`, `cohortSpec`, `statusFilter`, `cdrVersionName`, `pageToken`, `pageSize`, `fieldSet`){
      if (!missing(`cohortName`)) {
        stopifnot(is.character(`cohortName`), length(`cohortName`) == 1)
        self$`cohortName` <- `cohortName`
      }
      if (!missing(`cohortSpec`)) {
        stopifnot(is.character(`cohortSpec`), length(`cohortSpec`) == 1)
        self$`cohortSpec` <- `cohortSpec`
      }
      if (!missing(`statusFilter`)) {
        stopifnot(is.list(`statusFilter`), length(`statusFilter`) != 0)
        lapply(`statusFilter`, function(x) stopifnot(R6::is.R6(x)))
        self$`statusFilter` <- `statusFilter`
      }
      if (!missing(`cdrVersionName`)) {
        stopifnot(is.character(`cdrVersionName`), length(`cdrVersionName`) == 1)
        self$`cdrVersionName` <- `cdrVersionName`
      }
      if (!missing(`pageToken`)) {
        stopifnot(is.character(`pageToken`), length(`pageToken`) == 1)
        self$`pageToken` <- `pageToken`
      }
      if (!missing(`pageSize`)) {
        stopifnot(is.numeric(`pageSize`), length(`pageSize`) == 1)
        self$`pageSize` <- `pageSize`
      }
      if (!missing(`fieldSet`)) {
        stopifnot(R6::is.R6(`fieldSet`))
        self$`fieldSet` <- `fieldSet`
      }
    },
    toJSON = function() {
      MaterializeCohortRequestObject <- list()
      if (!is.null(self$`cohortName`)) {
        MaterializeCohortRequestObject[['cohortName']] <- self$`cohortName`
      }
      if (!is.null(self$`cohortSpec`)) {
        MaterializeCohortRequestObject[['cohortSpec']] <- self$`cohortSpec`
      }
      if (!is.null(self$`statusFilter`)) {
        MaterializeCohortRequestObject[['statusFilter']] <- lapply(self$`statusFilter`, function(x) x$toJSON())
      }
      if (!is.null(self$`cdrVersionName`)) {
        MaterializeCohortRequestObject[['cdrVersionName']] <- self$`cdrVersionName`
      }
      if (!is.null(self$`pageToken`)) {
        MaterializeCohortRequestObject[['pageToken']] <- self$`pageToken`
      }
      if (!is.null(self$`pageSize`)) {
        MaterializeCohortRequestObject[['pageSize']] <- self$`pageSize`
      }
      if (!is.null(self$`fieldSet`)) {
        MaterializeCohortRequestObject[['fieldSet']] <- self$`fieldSet`$toJSON()
      }

      MaterializeCohortRequestObject
    },
    fromJSON = function(MaterializeCohortRequestJson) {
      MaterializeCohortRequestObject <- jsonlite::fromJSON(MaterializeCohortRequestJson)
      if (!is.null(MaterializeCohortRequestObject$`cohortName`)) {
        self$`cohortName` <- MaterializeCohortRequestObject$`cohortName`
      }
      if (!is.null(MaterializeCohortRequestObject$`cohortSpec`)) {
        self$`cohortSpec` <- MaterializeCohortRequestObject$`cohortSpec`
      }
      if (!is.null(MaterializeCohortRequestObject$`statusFilter`)) {
        self$`statusFilter` <- lapply(MaterializeCohortRequestObject$`statusFilter`, function(x) {
          statusFilterObject <- CohortStatus$new()
          statusFilterObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          statusFilterObject
        })
      }
      if (!is.null(MaterializeCohortRequestObject$`cdrVersionName`)) {
        self$`cdrVersionName` <- MaterializeCohortRequestObject$`cdrVersionName`
      }
      if (!is.null(MaterializeCohortRequestObject$`pageToken`)) {
        self$`pageToken` <- MaterializeCohortRequestObject$`pageToken`
      }
      if (!is.null(MaterializeCohortRequestObject$`pageSize`)) {
        self$`pageSize` <- MaterializeCohortRequestObject$`pageSize`
      }
      if (!is.null(MaterializeCohortRequestObject$`fieldSet`)) {
        fieldSetObject <- FieldSet$new()
        fieldSetObject$fromJSON(jsonlite::toJSON(MaterializeCohortRequestObject$fieldSet, auto_unbox = TRUE))
        self$`fieldSet` <- fieldSetObject
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "cohortName": %s,
           "cohortSpec": %s,
           "statusFilter": [%s],
           "cdrVersionName": %s,
           "pageToken": %s,
           "pageSize": %s,
           "fieldSet": %s
        }',
        self$`cohortName`,
        self$`cohortSpec`,
        lapply(self$`statusFilter`, function(x) paste(x$toJSON(), sep=",")),
        self$`cdrVersionName`,
        self$`pageToken`,
        self$`pageSize`,
        self$`fieldSet`$toJSON()
      )
    },
    fromJSONString = function(MaterializeCohortRequestJson) {
      MaterializeCohortRequestObject <- jsonlite::fromJSON(MaterializeCohortRequestJson)
      self$`cohortName` <- MaterializeCohortRequestObject$`cohortName`
      self$`cohortSpec` <- MaterializeCohortRequestObject$`cohortSpec`
      self$`statusFilter` <- lapply(MaterializeCohortRequestObject$`statusFilter`, function(x) CohortStatus$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
      self$`cdrVersionName` <- MaterializeCohortRequestObject$`cdrVersionName`
      self$`pageToken` <- MaterializeCohortRequestObject$`pageToken`
      self$`pageSize` <- MaterializeCohortRequestObject$`pageSize`
      FieldSetObject <- FieldSet$new()
      self$`fieldSet` <- FieldSetObject$fromJSON(jsonlite::toJSON(MaterializeCohortRequestObject$fieldSet, auto_unbox = TRUE))
    }
  )
)
