# AllOfUs Client API
#
# The API used by AllOfUs workbench clients (including both notebooks and our UI.)
#
# OpenAPI spec version: 0.1.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' MaterializeCohortResponse Class
#'
#' @field results 
#' @field nextPageToken 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
MaterializeCohortResponse <- R6::R6Class(
  'MaterializeCohortResponse',
  public = list(
    `results` = NULL,
    `nextPageToken` = NULL,
    initialize = function(`results`, `nextPageToken`){
      if (!missing(`results`)) {
        stopifnot(is.list(`results`), length(`results`) != 0)
        lapply(`results`, function(x) stopifnot(R6::is.R6(x)))
        self$`results` <- `results`
      }
      if (!missing(`nextPageToken`)) {
        stopifnot(is.character(`nextPageToken`), length(`nextPageToken`) == 1)
        self$`nextPageToken` <- `nextPageToken`
      }
    },
    toJSON = function() {
      MaterializeCohortResponseObject <- list()
      if (!is.null(self$`results`)) {
        MaterializeCohortResponseObject[['results']] <- lapply(self$`results`, function(x) x$toJSON())
      }
      if (!is.null(self$`nextPageToken`)) {
        MaterializeCohortResponseObject[['nextPageToken']] <- self$`nextPageToken`
      }

      MaterializeCohortResponseObject
    },
    fromJSON = function(MaterializeCohortResponseJson) {
      MaterializeCohortResponseObject <- jsonlite::fromJSON(MaterializeCohortResponseJson)
      if (!is.null(MaterializeCohortResponseObject$`results`)) {
        self$`results` <- lapply(MaterializeCohortResponseObject$`results`, function(x) {
          resultsObject <- TODO_OBJECT_MAPPING$new()
          resultsObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          resultsObject
        })
      }
      if (!is.null(MaterializeCohortResponseObject$`nextPageToken`)) {
        self$`nextPageToken` <- MaterializeCohortResponseObject$`nextPageToken`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "results": [%s],
           "nextPageToken": %s
        }',
        lapply(self$`results`, function(x) paste(x$toJSON(), sep=",")),
        self$`nextPageToken`
      )
    },
    fromJSONString = function(MaterializeCohortResponseJson) {
      MaterializeCohortResponseObject <- jsonlite::fromJSON(MaterializeCohortResponseJson)
      self$`results` <- lapply(MaterializeCohortResponseObject$`results`, function(x) TODO_OBJECT_MAPPING$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
      self$`nextPageToken` <- MaterializeCohortResponseObject$`nextPageToken`
    }
  )
)
