# AllOfUs Client API
#
# The API used by AllOfUs workbench clients (including both notebooks and our UI.)
#
# OpenAPI spec version: 0.1.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' Operator Class
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Operator <- R6::R6Class(
  'Operator',
  public = list(
    initialize = function(){
    },
    toJSON = function() {
      OperatorObject <- list()

      OperatorObject
    },
    fromJSON = function(OperatorJson) {
      OperatorObject <- jsonlite::fromJSON(OperatorJson)
    },
    toJSONString = function() {
       sprintf(
        '{
        }',
      )
    },
    fromJSONString = function(OperatorJson) {
      OperatorObject <- jsonlite::fromJSON(OperatorJson)
    }
  )
)
