# AllOfUs Client API
#
# The API used by AllOfUs workbench clients (including both notebooks and our UI.)
#
# OpenAPI spec version: 0.1.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' ResultFilters Class
#'
#' @field if_not 
#' @field allOf 
#' @field anyOf 
#' @field columnFilter 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ResultFilters <- R6::R6Class(
  'ResultFilters',
  public = list(
    `if_not` = NULL,
    `allOf` = NULL,
    `anyOf` = NULL,
    `columnFilter` = NULL,
    initialize = function(`if_not`, `allOf`, `anyOf`, `columnFilter`){
      if (!missing(`if_not`)) {
        self$`if_not` <- `if_not`
      }
      if (!missing(`allOf`)) {
        stopifnot(is.list(`allOf`), length(`allOf`) != 0)
        lapply(`allOf`, function(x) stopifnot(R6::is.R6(x)))
        self$`allOf` <- `allOf`
      }
      if (!missing(`anyOf`)) {
        stopifnot(is.list(`anyOf`), length(`anyOf`) != 0)
        lapply(`anyOf`, function(x) stopifnot(R6::is.R6(x)))
        self$`anyOf` <- `anyOf`
      }
      if (!missing(`columnFilter`)) {
        stopifnot(R6::is.R6(`columnFilter`))
        self$`columnFilter` <- `columnFilter`
      }
    },
    toJSON = function() {
      ResultFiltersObject <- list()
      if (!is.null(self$`if_not`)) {
        ResultFiltersObject[['if_not']] <- self$`if_not`
      }
      if (!is.null(self$`allOf`)) {
        ResultFiltersObject[['allOf']] <- lapply(self$`allOf`, function(x) x$toJSON())
      }
      if (!is.null(self$`anyOf`)) {
        ResultFiltersObject[['anyOf']] <- lapply(self$`anyOf`, function(x) x$toJSON())
      }
      if (!is.null(self$`columnFilter`)) {
        ResultFiltersObject[['columnFilter']] <- self$`columnFilter`$toJSON()
      }

      ResultFiltersObject
    },
    fromJSON = function(ResultFiltersJson) {
      ResultFiltersObject <- jsonlite::fromJSON(ResultFiltersJson)
      if (!is.null(ResultFiltersObject$`if_not`)) {
        self$`if_not` <- ResultFiltersObject$`if_not`
      }
      if (!is.null(ResultFiltersObject$`allOf`)) {
        self$`allOf` <- lapply(ResultFiltersObject$`allOf`, function(x) {
          allOfObject <- ResultFilters$new()
          allOfObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          allOfObject
        })
      }
      if (!is.null(ResultFiltersObject$`anyOf`)) {
        self$`anyOf` <- lapply(ResultFiltersObject$`anyOf`, function(x) {
          anyOfObject <- ResultFilters$new()
          anyOfObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          anyOfObject
        })
      }
      if (!is.null(ResultFiltersObject$`columnFilter`)) {
        columnFilterObject <- ColumnFilter$new()
        columnFilterObject$fromJSON(jsonlite::toJSON(ResultFiltersObject$columnFilter, auto_unbox = TRUE))
        self$`columnFilter` <- columnFilterObject
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "if_not": %s,
           "allOf": [%s],
           "anyOf": [%s],
           "columnFilter": %s
        }',
        self$`if_not`,
        lapply(self$`allOf`, function(x) paste(x$toJSON(), sep=",")),
        lapply(self$`anyOf`, function(x) paste(x$toJSON(), sep=",")),
        self$`columnFilter`$toJSON()
      )
    },
    fromJSONString = function(ResultFiltersJson) {
      ResultFiltersObject <- jsonlite::fromJSON(ResultFiltersJson)
      self$`if_not` <- ResultFiltersObject$`if_not`
      self$`allOf` <- lapply(ResultFiltersObject$`allOf`, function(x) ResultFilters$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
      self$`anyOf` <- lapply(ResultFiltersObject$`anyOf`, function(x) ResultFilters$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
      ColumnFilterObject <- ColumnFilter$new()
      self$`columnFilter` <- ColumnFilterObject$fromJSON(jsonlite::toJSON(ResultFiltersObject$columnFilter, auto_unbox = TRUE))
    }
  )
)
