# AllOfUs Client API
#
# The API used by AllOfUs workbench clients (including both notebooks and our UI.)
#
# OpenAPI spec version: 0.1.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' SearchConceptsRequest Class
#'
#' @field query 
#' @field standardConceptFilter 
#' @field vocabularyIds 
#' @field domain 
#' @field maxResults 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
SearchConceptsRequest <- R6::R6Class(
  'SearchConceptsRequest',
  public = list(
    `query` = NULL,
    `standardConceptFilter` = NULL,
    `vocabularyIds` = NULL,
    `domain` = NULL,
    `maxResults` = NULL,
    initialize = function(`query`, `standardConceptFilter`, `vocabularyIds`, `domain`, `maxResults`){
      if (!missing(`query`)) {
        stopifnot(is.character(`query`), length(`query`) == 1)
        self$`query` <- `query`
      }
      if (!missing(`standardConceptFilter`)) {
        stopifnot(R6::is.R6(`standardConceptFilter`))
        self$`standardConceptFilter` <- `standardConceptFilter`
      }
      if (!missing(`vocabularyIds`)) {
        stopifnot(is.list(`vocabularyIds`), length(`vocabularyIds`) != 0)
        lapply(`vocabularyIds`, function(x) stopifnot(is.character(x)))
        self$`vocabularyIds` <- `vocabularyIds`
      }
      if (!missing(`domain`)) {
        stopifnot(R6::is.R6(`domain`))
        self$`domain` <- `domain`
      }
      if (!missing(`maxResults`)) {
        stopifnot(is.numeric(`maxResults`), length(`maxResults`) == 1)
        self$`maxResults` <- `maxResults`
      }
    },
    toJSON = function() {
      SearchConceptsRequestObject <- list()
      if (!is.null(self$`query`)) {
        SearchConceptsRequestObject[['query']] <- self$`query`
      }
      if (!is.null(self$`standardConceptFilter`)) {
        SearchConceptsRequestObject[['standardConceptFilter']] <- self$`standardConceptFilter`$toJSON()
      }
      if (!is.null(self$`vocabularyIds`)) {
        SearchConceptsRequestObject[['vocabularyIds']] <- self$`vocabularyIds`
      }
      if (!is.null(self$`domain`)) {
        SearchConceptsRequestObject[['domain']] <- self$`domain`$toJSON()
      }
      if (!is.null(self$`maxResults`)) {
        SearchConceptsRequestObject[['maxResults']] <- self$`maxResults`
      }

      SearchConceptsRequestObject
    },
    fromJSON = function(SearchConceptsRequestJson) {
      SearchConceptsRequestObject <- jsonlite::fromJSON(SearchConceptsRequestJson)
      if (!is.null(SearchConceptsRequestObject$`query`)) {
        self$`query` <- SearchConceptsRequestObject$`query`
      }
      if (!is.null(SearchConceptsRequestObject$`standardConceptFilter`)) {
        standardConceptFilterObject <- StandardConceptFilter$new()
        standardConceptFilterObject$fromJSON(jsonlite::toJSON(SearchConceptsRequestObject$standardConceptFilter, auto_unbox = TRUE))
        self$`standardConceptFilter` <- standardConceptFilterObject
      }
      if (!is.null(SearchConceptsRequestObject$`vocabularyIds`)) {
        self$`vocabularyIds` <- SearchConceptsRequestObject$`vocabularyIds`
      }
      if (!is.null(SearchConceptsRequestObject$`domain`)) {
        domainObject <- Domain$new()
        domainObject$fromJSON(jsonlite::toJSON(SearchConceptsRequestObject$domain, auto_unbox = TRUE))
        self$`domain` <- domainObject
      }
      if (!is.null(SearchConceptsRequestObject$`maxResults`)) {
        self$`maxResults` <- SearchConceptsRequestObject$`maxResults`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "query": %s,
           "standardConceptFilter": %s,
           "vocabularyIds": [%s],
           "domain": %s,
           "maxResults": %s
        }',
        self$`query`,
        self$`standardConceptFilter`$toJSON(),
        lapply(self$`vocabularyIds`, function(x) paste(paste0('"', x, '"'), sep=",")),
        self$`domain`$toJSON(),
        self$`maxResults`
      )
    },
    fromJSONString = function(SearchConceptsRequestJson) {
      SearchConceptsRequestObject <- jsonlite::fromJSON(SearchConceptsRequestJson)
      self$`query` <- SearchConceptsRequestObject$`query`
      StandardConceptFilterObject <- StandardConceptFilter$new()
      self$`standardConceptFilter` <- StandardConceptFilterObject$fromJSON(jsonlite::toJSON(SearchConceptsRequestObject$standardConceptFilter, auto_unbox = TRUE))
      self$`vocabularyIds` <- SearchConceptsRequestObject$`vocabularyIds`
      DomainObject <- Domain$new()
      self$`domain` <- DomainObject$fromJSON(jsonlite::toJSON(SearchConceptsRequestObject$domain, auto_unbox = TRUE))
      self$`maxResults` <- SearchConceptsRequestObject$`maxResults`
    }
  )
)
