# AllOfUs Client API
#
# The API used by AllOfUs workbench clients (including both notebooks and our UI.)
#
# OpenAPI spec version: 0.1.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' StandardConceptFilter Class
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
StandardConceptFilter <- R6::R6Class(
  'StandardConceptFilter',
  public = list(
    initialize = function(){
    },
    toJSON = function() {
      StandardConceptFilterObject <- list()

      StandardConceptFilterObject
    },
    fromJSON = function(StandardConceptFilterJson) {
      StandardConceptFilterObject <- jsonlite::fromJSON(StandardConceptFilterJson)
    },
    toJSONString = function() {
       sprintf(
        '{
        }',
      )
    },
    fromJSONString = function(StandardConceptFilterJson) {
      StandardConceptFilterObject <- jsonlite::fromJSON(StandardConceptFilterJson)
    }
  )
)
