# AllOfUs Client API
#
# The API used by AllOfUs workbench clients (including both notebooks and our UI.)
#
# OpenAPI spec version: 0.1.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' TableQuery Class
#'
#' @field tableName 
#' @field columns 
#' @field filters 
#' @field orderBy 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
TableQuery <- R6::R6Class(
  'TableQuery',
  public = list(
    `tableName` = NULL,
    `columns` = NULL,
    `filters` = NULL,
    `orderBy` = NULL,
    initialize = function(`tableName`, `columns`, `filters`, `orderBy`){
      if (!missing(`tableName`)) {
        stopifnot(is.character(`tableName`), length(`tableName`) == 1)
        self$`tableName` <- `tableName`
      }
      if (!missing(`columns`)) {
        stopifnot(is.list(`columns`), length(`columns`) != 0)
        lapply(`columns`, function(x) stopifnot(is.character(x)))
        self$`columns` <- `columns`
      }
      if (!missing(`filters`)) {
        stopifnot(R6::is.R6(`filters`))
        self$`filters` <- `filters`
      }
      if (!missing(`orderBy`)) {
        stopifnot(is.list(`orderBy`), length(`orderBy`) != 0)
        lapply(`orderBy`, function(x) stopifnot(is.character(x)))
        self$`orderBy` <- `orderBy`
      }
    },
    toJSON = function() {
      TableQueryObject <- list()
      if (!is.null(self$`tableName`)) {
        TableQueryObject[['tableName']] <- self$`tableName`
      }
      if (!is.null(self$`columns`)) {
        TableQueryObject[['columns']] <- self$`columns`
      }
      if (!is.null(self$`filters`)) {
        TableQueryObject[['filters']] <- self$`filters`$toJSON()
      }
      if (!is.null(self$`orderBy`)) {
        TableQueryObject[['orderBy']] <- self$`orderBy`
      }

      TableQueryObject
    },
    fromJSON = function(TableQueryJson) {
      TableQueryObject <- jsonlite::fromJSON(TableQueryJson)
      if (!is.null(TableQueryObject$`tableName`)) {
        self$`tableName` <- TableQueryObject$`tableName`
      }
      if (!is.null(TableQueryObject$`columns`)) {
        self$`columns` <- TableQueryObject$`columns`
      }
      if (!is.null(TableQueryObject$`filters`)) {
        filtersObject <- ResultFilters$new()
        filtersObject$fromJSON(jsonlite::toJSON(TableQueryObject$filters, auto_unbox = TRUE))
        self$`filters` <- filtersObject
      }
      if (!is.null(TableQueryObject$`orderBy`)) {
        self$`orderBy` <- TableQueryObject$`orderBy`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "tableName": %s,
           "columns": [%s],
           "filters": %s,
           "orderBy": [%s]
        }',
        self$`tableName`,
        lapply(self$`columns`, function(x) paste(paste0('"', x, '"'), sep=",")),
        self$`filters`$toJSON(),
        lapply(self$`orderBy`, function(x) paste(paste0('"', x, '"'), sep=","))
      )
    },
    fromJSONString = function(TableQueryJson) {
      TableQueryObject <- jsonlite::fromJSON(TableQueryJson)
      self$`tableName` <- TableQueryObject$`tableName`
      self$`columns` <- TableQueryObject$`columns`
      ResultFiltersObject <- ResultFilters$new()
      self$`filters` <- ResultFiltersObject$fromJSON(jsonlite::toJSON(TableQueryObject$filters, auto_unbox = TRUE))
      self$`orderBy` <- TableQueryObject$`orderBy`
    }
  )
)
