version: 2

defaults: &defaults
  docker:
    - image: allofustest/pyclient:buildimage-1.1.2
  working_directory: ~/pyclient

jobs:
  test:
     <<: *defaults
     steps:
      - checkout
      - run:
          command: git submodule update --init --recursive
      - run:
          command: ci/activate_creds.sh circle-sa-key.json
      - run:
          command: python3 -m venv venv
      - run:
          command: |
            . venv/bin/activate
            ./project.rb setup-env
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            ./project.rb test

workflows:
  version: 2
  test:
    jobs:
      - test

experimental:
  notify:
    branches:
      only:
        - master
